// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD9Uz88RJUVSWwF_heLM6RInT7gTyMqLM',
    appId: '1:967947462817:web:40639ecc055441ea72a8e0',
    messagingSenderId: '967947462817',
    projectId: 'androidnewapp',
    authDomain: 'androidnewapp.firebaseapp.com',
    storageBucket: 'androidnewapp.firebasestorage.app',
    measurementId: 'G-CF1LNNWBCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx8zgWVm5kn-U30FmIYqSEIadtkXX16-U',
    appId: '1:967947462817:android:963d36a38ec8ebd472a8e0',
    messagingSenderId: '967947462817',
    projectId: 'androidnewapp',
    storageBucket: 'androidnewapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmH5SV9VM7R1qYvh-d9968UPlvq7JGWwg',
    appId: '1:967947462817:ios:43669a3028c5e61d72a8e0',
    messagingSenderId: '967947462817',
    projectId: 'androidnewapp',
    storageBucket: 'androidnewapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationLec04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmH5SV9VM7R1qYvh-d9968UPlvq7JGWwg',
    appId: '1:967947462817:ios:43669a3028c5e61d72a8e0',
    messagingSenderId: '967947462817',
    projectId: 'androidnewapp',
    storageBucket: 'androidnewapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationLec04',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD9Uz88RJUVSWwF_heLM6RInT7gTyMqLM',
    appId: '1:967947462817:web:3ddd56335f48366172a8e0',
    messagingSenderId: '967947462817',
    projectId: 'androidnewapp',
    authDomain: 'androidnewapp.firebaseapp.com',
    storageBucket: 'androidnewapp.firebasestorage.app',
    measurementId: 'G-5BXC59PB3J',
  );
}
